// <auto-generated />
using System;
using Guide.VariacaoAtivo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guide.VariacaoAtivo.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128203526_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Guide.VariacaoAtivo.Domain.Models.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Dia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dia"), 1L, 1);

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(6,3)");

                    b.Property<decimal>("VariacaoDiaAnterior")
                        .HasColumnType("DECIMAL(8,6)");

                    b.Property<decimal>("VariacaoPrimeiraData")
                        .HasColumnType("DECIMAL(8,6)");

                    b.HasKey("Id");

                    b.ToTable("TB_VARIACAO_ATIVOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
